services:
  ariang:
    image: httpd:2.4
    container_name: ariang
    ports:
      - "21000:80"
    volumes:
      - "/home/hades/Programming/AriaNg/AriaNg-latest:/usr/local/apache2/htdocs/"
    restart: "unless-stopped"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ariang.rule=Host(`ariang.hades-linux-mbp.lan`)"
      - "traefik.http.routers.ariang.entrypoints=web"
      - "traefik.http.services.ariang.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
    name: traefik_proxy
