# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
# Copy this file to secrets.yaml and adjust your credentials.
some_password: your_secret_password_here
