global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.0.7:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.0.7:9400']
        
  - job_name: 'process-exporter'
    static_configs:
      - targets: ['192.168.0.7:9256']

  - job_name: 'doorbell-detector'
    static_configs:
      - targets: ['192.168.0.7:10001']  
