services:
  gotify:
    image: gotify/server
    container_name: gotify_server
    ports:
      - 3003:80  # Change the external port to 3003
    environment:
      GOTIFY_DEFAULTUSER_PASS: 'admin'
      TZ: 'Asia/Kolkata'  # Set the timezone for India
    volumes:
      - data:/app/data  # Use a Docker volume named 'data'

volumes:
  data:  # Define the Docker volume
