services:
  gotify:
    image: gotify/server
    container_name: gotify_server
    ports:
      - 3004:80
    environment:
      GOTIFY_DEFAULTUSER_PASS: 'admin'
      TZ: 'Asia/Kolkata'  # Set the timezone for India
    volumes:
      - data:/app/data  # Use a Docker volume named 'data'
    networks:
      - traefik_proxy
    restart: unless-stopped

volumes:
  data:  # Define the Docker volume

networks:
  traefik_proxy:
    external: true
