services:
  gotify:
    image: gotify/server
    container_name: gotify_server
    ports:
      - 3004:80
    environment:
      GOTIFY_DEFAULTUSER_PASS: ${GOTIFY_DEFAULTUSER_PASS:-admin}
      TZ: ${TZ:-Asia/Kolkata}
    volumes:
      - data:/app/data  # Use a Docker volume named 'data'
    networks:
      - traefik_proxy
    restart: unless-stopped

volumes:
  data:  # Define the Docker volume

networks:
  traefik_proxy:
    external: true
