services:
  audio_server:
    container_name: doorbell-detector
    build: 
      context: .
      dockerfile: Dockerfile
    image: doorbell-detector:2.5.0
    ports:
      - "3003:3003"
      - "10001:8000"
    environment:
      - TZ=Asia/Kolkata
      - CUDA_VISIBLE_DEVICES=-1  
    restart: unless-stopped
