services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-storage:/var/lib/grafana
    configs:
      - source: grafana.ini
        target: /etc/grafana/grafana.ini
    restart: unless-stopped 
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.hades-linux-mbp.lan`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"    

volumes:
  grafana-storage:
    external: true

configs:
  grafana.ini:
    content: |
      [feature_toggles]
      accessControlOnCall = false


networks:
  traefik_proxy:
    external: true
    name: traefik_proxy