# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "192.168.0.13:53:53/tcp"
      - "192.168.0.13:53:53/udp"
      - "192.168.0.13:8100:80"
    environment:
      - TZ=Asia/Kolkata
      - DNS1=8.8.8.8
      - DNS2=8.8.4.4
    volumes:
      - 'pihole_data:/etc/pihole'
      - 'dnsmasq_data:/etc/dnsmasq.d'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "pi.hole"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.hades-linux-mbp.lan`)"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

volumes:
  pihole_data:
  dnsmasq_data:

networks:
  traefik_proxy:
    external: true
    name: traefik_proxy