# HTTP redirect for all domains
server {
    listen 80;
    server_name hades-linux-mbp.local *.hades-linux-mbp.local;
    return 301 https://$host$request_uri;
}

# Main server
server {
    listen 443 ssl;
    listen 443 quic reuseport;
    server_name hades-linux-mbp.local;

    ssl_certificate /etc/nginx/tls/nginx.crt;
    ssl_trusted_certificate /etc/nginx/tls/nginx.crt;
    ssl_certificate_key /etc/nginx/tls/nginx.key;
    ssl_protocols TLSv1.3;
    add_header Alt-Svc 'h3=":443"; ma=86400' always;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    location / {
        root /usr/share/nginx/html;
        index services.html;
    }

    location /jsonrpc {
        proxy_pass http://192.168.0.7:6800;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Grafana
server {
    listen 443 ssl;
    listen 443 quic;
    server_name grafana.hades-linux-mbp.local;

    ssl_certificate /etc/nginx/tls/nginx.crt;
    ssl_trusted_certificate /etc/nginx/tls/nginx.crt;
    ssl_certificate_key /etc/nginx/tls/nginx.key;
    ssl_protocols TLSv1.3;
    add_header Alt-Svc 'h3=":443"; ma=86400' always;

    location / {
        proxy_pass http://172.17.0.1:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Prometheus
server {
    listen 443 ssl;
    listen 443 quic;
    server_name prometheus.hades-linux-mbp.local;

    ssl_certificate /etc/nginx/tls/nginx.crt;
    ssl_trusted_certificate /etc/nginx/tls/nginx.crt;
    ssl_certificate_key /etc/nginx/tls/nginx.key;
    ssl_protocols TLSv1.3;
    add_header Alt-Svc 'h3=":443"; ma=86400' always;

    location / {
        proxy_pass http://172.17.0.1:9090/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# HTTPD
server {
    listen 443 ssl;
    listen 443 quic;
    server_name httpd.hades-linux-mbp.local;

    ssl_certificate /etc/nginx/tls/nginx.crt;
    ssl_trusted_certificate /etc/nginx/tls/nginx.crt;
    ssl_certificate_key /etc/nginx/tls/nginx.key;
    ssl_protocols TLSv1.3;
    add_header Alt-Svc 'h3=":443"; ma=86400' always;

    location / {
        proxy_pass http://172.17.0.1:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Flask
server {
    listen 443 ssl;
    listen 443 quic;
    server_name flask.hades-linux-mbp.local;

    ssl_certificate /etc/nginx/tls/nginx.crt;
    ssl_trusted_certificate /etc/nginx/tls/nginx.crt;
    ssl_certificate_key /etc/nginx/tls/nginx.key;
    ssl_protocols TLSv1.3;
    add_header Alt-Svc 'h3=":443"; ma=86400' always;

    location / {
        proxy_pass http://172.17.0.1:8123/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# cAdvisor
server {
    listen 443 ssl;
    listen 443 quic;
    server_name cadvisor.hades-linux-mbp.local;

    ssl_certificate /etc/nginx/tls/nginx.crt;
    ssl_trusted_certificate /etc/nginx/tls/nginx.crt;
    ssl_certificate_key /etc/nginx/tls/nginx.key;
    ssl_protocols TLSv1.3;
    add_header Alt-Svc 'h3=":443"; ma=86400' always;

    location / {
        proxy_pass http://172.17.0.1:9400/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# Mantis
server {
    listen 443 ssl;
    listen 443 quic;
    server_name mantis.hades-linux-mbp.local;

    ssl_certificate /etc/nginx/tls/nginx.crt;
    ssl_trusted_certificate /etc/nginx/tls/nginx.crt;
    ssl_certificate_key /etc/nginx/tls/nginx.key;
    ssl_protocols TLSv1.3;
    add_header Alt-Svc 'h3=":443"; ma=86400' always;

    location / {
        proxy_pass http://172.17.0.1:4000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

