services:
  tuya-python-exporter:
    build: .
    container_name: tuya-python-exporter
    restart: unless-stopped
    ports:
      - "9876:9876"
    environment:
      - EXPORTER_PORT=9876
      - SCRAPE_INTERVAL=10
      - LOG_LEVEL=INFO
      - TUYA_DEVICES_CONFIG_PATH=/app/devices.json
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./devices.json:/app/devices.json:ro
